### PR TITLE
Fixed a few broken links

### PR DESCRIPTION
**Pull request by CraftyClark**
Not sure these changes are complete. But did a few :P
Cheers

### CODE REVIEW

**Comment by darioblanco** [comment]
Oh! Thanks for this change! I actually forgot I had this dependency when I switched my github account name :)

**Comment by CraftyClark** [comment]
haha yep no problem man! :) I'm enjoying your article over at http://thesoftjaguar.com/posts/2014/03/04/sublime3-and-python/
I'm using my sublime3 text editor for python for the first time and I think I need to change a few preferences. Such as your recommended 
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
👍 
/ trying to figure out how to use anaconda package usefully :P

**Comment by darioblanco** [comment]
If you need help let me know! I am glad people put effort in code standards like typing always 4 spaces instead of tabs, especially when I put visibility in my IDE for tabs and spaces (so it looks very ugly when people mixed both).

Anaconda is a great package, very helpful for writing clean python code!

**Comment by CraftyClark** [comment]
well.. since you offered :)
Do you have a recommended way for debugging python code while developing w/ sublime3?
How do you like to do it? Is there a nice way to do it using sublime3 somehow or do I need to download a separate debugger utility? 
Thanks!

**Comment by darioblanco** [comment]
I always debug my Python applications using a virtualenv and creating unit tests on the go with pytest (running them on the console). If you want to be more advanced with test environments you can use tox (that creates the virtualenvs for you). This is a bit more complicated set up but is really worth it (other people just use docker directly, which is a nice alternative).

So with Sublime 3 I just limit the IDE to tell me whenever I am not compliant with PEP3 and pylint. Running the code is out of Sublime's scope in my case.

**Comment by CraftyClark** [comment]
I appreciate the suggestions!
I'll definitely look into learning how to use gdb within virtualenv to debug from the console. 
That sounds like just what I'm looking for :)
Happy coding, and I'll keep a look out for your next blog post. 
Cheers

**Pull request merged**
